name: Flutter CI/CD

on:
  push:
    branches: [ "build" ]
#  pull_request:
#    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install & cache Flutter SDK automatically
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true  # Enable the built-in SDK caching

      # 2) Cache Dart/Flutter packages (Choose your preferred path)
      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            .dart_tool
            # Or ~/.pub-cache on Linux:
            # $HOME/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 3) Install dependencies
      - name: Get dependencies
        run: flutter pub get

      - name: Decode and create .env_prod
        run: |
          mkdir -p env
          echo "${{ secrets.ENV_PROD_B64 }}" | base64 --decode > env/.env_prod

      # 4) Run your build, tests, analysis, etc.
      - name: Build APK
        run: flutter build apk

      # Upload APK as artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Notify in Microsoft Teams
      - name: Send message to Microsoft Teams with link to Actions
        run: |
          curl -H 'Content-Type: application/json' \
            -d '{
              "@type": "MessageCard",
              "@context": "https://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "Flutter CI/CD",
              "title": "🚀 Flutter CI/CD Build Completed",
              "sections": [{
                "activityTitle": "**APK Build Successful**",
                "text": "The APK has been built and uploaded as an artifact."
              }],
              "potentialAction": [{
                "@type": "OpenUri",
                "name": "🔗 View Build & Download APK",
                "targets": [
                  { "os": "default", "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }
                ]
              }]
            }' \
            ${{ secrets.TEAMS_WEBHOOK_URL }}
      
