name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install & cache Flutter SDK automatically
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true  # Enable the built-in SDK caching

      # 2) Cache Dart/Flutter packages (Choose your preferred path)
      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            .dart_tool
            # Or ~/.pub-cache on Linux:
            # $HOME/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 3) Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # 4) Run your build, tests, analysis, etc.
      - name: Build APK
        run: flutter build apk 

      - name: Analyze code
        run: flutter analyze
